Collections:
  - Name: RTMDet
    Metadata:
      Training Data: COCO
      Training Techniques:
        - AdamW
        - Flat Cosine Annealing
      Training Resources: 8x A100 GPUs
      Architecture:
        - CSPNeXt
        - CSPNeXtPAFPN
    README: configs/rtmdet/README.md
    Code:
      URL: https://github.com/open-mmlab/mmdetection/blob/v3.0.0rc1/mmdet/models/detectors/rtmdet.py#L6
      Version: v3.0.0rc1

Models:
  - Name: rtmdet_tiny_8xb32-300e_coco
    Alias:
      - rtmdet-t
    In Collection: RTMDet
    Config: configs/rtmdet/rtmdet_tiny_8xb32-300e_coco.py
    Metadata:
      Training Memory (GB): 11.7
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 40.9
    Weights: https://download.openmmlab.com/mmdetection/v3.0/rtmdet/rtmdet_tiny_8xb32-300e_coco/rtmdet_tiny_8xb32-300e_coco_20220902_112414-78e30dcc.pth

  - Name: rtmdet_s_8xb32-300e_coco
    Alias:
      - rtmdet-s
    In Collection: RTMDet
    Config: configs/rtmdet/rtmdet_s_8xb32-300e_coco.py
    Metadata:
      Training Memory (GB): 15.9
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 44.5
    Weights: https://download.openmmlab.com/mmdetection/v3.0/rtmdet/rtmdet_s_8xb32-300e_coco/rtmdet_s_8xb32-300e_coco_20220905_161602-387a891e.pth

  - Name: rtmdet_m_8xb32-300e_coco
    Alias:
      - rtmdet-m
    In Collection: RTMDet
    Config: configs/rtmdet/rtmdet_m_8xb32-300e_coco.py
    Metadata:
      Training Memory (GB): 27.8
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 49.1
    Weights: https://download.openmmlab.com/mmdetection/v3.0/rtmdet/rtmdet_m_8xb32-300e_coco/rtmdet_m_8xb32-300e_coco_20220719_112220-229f527c.pth

  - Name: rtmdet_l_8xb32-300e_coco
    Alias:
      - rtmdet-l
    In Collection: RTMDet
    Config: configs/rtmdet/rtmdet_l_8xb32-300e_coco.py
    Metadata:
      Training Memory (GB): 43.2
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 51.3
    Weights: https://download.openmmlab.com/mmdetection/v3.0/rtmdet/rtmdet_l_8xb32-300e_coco/rtmdet_l_8xb32-300e_coco_20220719_112030-5a0be7c4.pth

  - Name: rtmdet_x_8xb32-300e_coco
    Alias:
      - rtmdet-x
    In Collection: RTMDet
    Config: configs/rtmdet/rtmdet_x_8xb32-300e_coco.py
    Metadata:
      Training Memory (GB): 61.1
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 52.6
    Weights: https://download.openmmlab.com/mmdetection/v3.0/rtmdet/rtmdet_x_8xb32-300e_coco/rtmdet_x_8xb32-300e_coco_20220715_230555-cc79b9ae.pth

  - Name: rtmdet_x_p6_4xb8-300e_coco
    Alias:
      - rtmdet-x_p6
    In Collection: RTMDet
    Config: configs/rtmdet/rtmdet_x_p6_4xb8-300e_coco.py
    Metadata:
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 54.9
    Weights: https://github.com/orange0-jp/orange-weights/releases/download/v0.1.0rtmdet-p6/rtmdet_x_p6_4xb8-300e_coco-bf32be58.pth

  - Name: rtmdet_l_convnext_b_4xb32-100e_coco
    Alias:
      - rtmdet-l_convnext_b
    In Collection: RTMDet
    Config: configs/rtmdet/rtmdet_l_convnext_b_4xb32-100e_coco.py
    Metadata:
      Epochs: 100
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 53.1
    Weights: https://github.com/orange0-jp/orange-weights/releases/download/v0.1.0rtmdet-swin-convnext/rtmdet_l_convnext_b_4xb32-100e_coco-d4731b3d.pth

  - Name: rtmdet_l_swin_b_4xb32-100e_coco
    Alias:
      - rtmdet-l_swin_b
    In Collection: RTMDet
    Config: configs/rtmdet/rtmdet_l_swin_b_4xb32-100e_coco.py
    Metadata:
      Epochs: 100
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 52.4
    Weights: https://github.com/orange0-jp/orange-weights/releases/download/v0.1.0rtmdet-swin-convnext/rtmdet_l_swin_b_4xb32-100e_coco-0828ce5d.pth

  - Name: rtmdet_l_swin_b_p6_4xb16-100e_coco
    Alias:
      - rtmdet-l_swin_b_p6
    In Collection: RTMDet
    Config: configs/rtmdet/rtmdet_l_swin_b_p6_4xb16-100e_coco.py
    Metadata:
      Epochs: 100
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 56.4
    Weights: https://github.com/orange0-jp/orange-weights/releases/download/v0.1.0rtmdet-swin-convnext/rtmdet_l_swin_b_p6_4xb16-100e_coco-a1486b6f.pth

  - Name: rtmdet-ins_tiny_8xb32-300e_coco
    Alias:
      - rtmdet-ins-t
    In Collection: RTMDet
    Config: configs/rtmdet/rtmdet-ins_tiny_8xb32-300e_coco.py
    Metadata:
      Training Memory (GB): 18.4
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 40.5
      - Task: Instance Segmentation
        Dataset: COCO
        Metrics:
          mask AP: 35.4
    Weights: https://download.openmmlab.com/mmdetection/v3.0/rtmdet/rtmdet-ins_tiny_8xb32-300e_coco/rtmdet-ins_tiny_8xb32-300e_coco_20221130_151727-ec670f7e.pth

  - Name: rtmdet-ins_s_8xb32-300e_coco
    Alias:
      - rtmdet-ins-s
    In Collection: RTMDet
    Config: configs/rtmdet/rtmdet-ins_s_8xb32-300e_coco.py
    Metadata:
      Training Memory (GB): 27.6
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 44.0
      - Task: Instance Segmentation
        Dataset: COCO
        Metrics:
          mask AP: 38.7
    Weights: https://download.openmmlab.com/mmdetection/v3.0/rtmdet/rtmdet-ins_s_8xb32-300e_coco/rtmdet-ins_s_8xb32-300e_coco_20221121_212604-fdc5d7ec.pth

  - Name: rtmdet-ins_m_8xb32-300e_coco
    Alias:
      - rtmdet-ins-m
    In Collection: RTMDet
    Config: configs/rtmdet/rtmdet-ins_m_8xb32-300e_coco.py
    Metadata:
      Training Memory (GB): 42.5
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 48.8
      - Task: Instance Segmentation
        Dataset: COCO
        Metrics:
          mask AP: 42.1
    Weights: https://download.openmmlab.com/mmdetection/v3.0/rtmdet/rtmdet-ins_m_8xb32-300e_coco/rtmdet-ins_m_8xb32-300e_coco_20221123_001039-6eba602e.pth

  - Name: rtmdet-ins_l_8xb32-300e_coco
    Alias:
      - rtmdet-ins-l
    In Collection: RTMDet
    Config: configs/rtmdet/rtmdet-ins_l_8xb32-300e_coco.py
    Metadata:
      Training Memory (GB): 59.8
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 51.2
      - Task: Instance Segmentation
        Dataset: COCO
        Metrics:
          mask AP: 43.7
    Weights: https://download.openmmlab.com/mmdetection/v3.0/rtmdet/rtmdet-ins_l_8xb32-300e_coco/rtmdet-ins_l_8xb32-300e_coco_20221124_103237-78d1d652.pth

  - Name: rtmdet-ins_x_8xb16-300e_coco
    Alias:
      - rtmdet-ins-x
    In Collection: RTMDet
    Config: configs/rtmdet/rtmdet-ins_x_8xb16-300e_coco.py
    Metadata:
      Training Memory (GB): 33.7
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 52.4
      - Task: Instance Segmentation
        Dataset: COCO
        Metrics:
          mask AP: 44.6
    Weights: https://download.openmmlab.com/mmdetection/v3.0/rtmdet/rtmdet-ins_x_8xb16-300e_coco/rtmdet-ins_x_8xb16-300e_coco_20221124_111313-33d4595b.pth
