- Name: retinanet_r50_fpn_1x_objects365v1
  In Collection: RetinaNet
  Config: configs/objects365/retinanet_r50_fpn_1x_objects365v1.py
  Metadata:
    Training Memory (GB): 7.4
    Epochs: 12
    Training Data: Objects365 v1
    Training Techniques:
      - SGD with Momentum
      - Weight Decay
  Results:
  - Task: Object Detection
    Dataset: Objects365 v1
    Metrics:
      box AP: 14.8
  Weights: https://download.openmmlab.com/mmdetection/v2.0/objects365/retinanet_r50_fpn_1x_obj365v1/retinanet_r50_fpn_1x_obj365v1_20221219_181859-ba3e3dd5.pth

- Name: retinanet_r50-syncbn_fpn_1350k_objects365v1
  In Collection: RetinaNet
  Config: configs/objects365/retinanet_r50-syncbn_fpn_1350k_objects365v1.py
  Metadata:
    Training Memory (GB): 7.6
    Iterations: 1350000
    Training Data: Objects365 v1
    Training Techniques:
      - SGD with Momentum
      - Weight Decay
  Results:
  - Task: Object Detection
    Dataset: Objects365 v1
    Metrics:
      box AP: 18.0
  Weights: https://download.openmmlab.com/mmdetection/v2.0/objects365/retinanet_r50_fpn_syncbn_1350k_obj365v1/retinanet_r50_fpn_syncbn_1350k_obj365v1_20220513_111237-7517c576.pth

- Name: retinanet_r50_fpn_1x_objects365v2
  In Collection: RetinaNet
  Config: configs/objects365/retinanet_r50_fpn_1x_objects365v2.py
  Metadata:
    Training Memory (GB): 7.2
    Epochs: 12
    Training Data: Objects365 v2
    Training Techniques:
      - SGD with Momentum
      - Weight Decay
  Results:
  - Task: Object Detection
    Dataset: Objects365 v2
    Metrics:
      box AP: 16.7
  Weights: https://download.openmmlab.com/mmdetection/v2.0/objects365/retinanet_r50_fpn_1x_obj365v2/retinanet_r50_fpn_1x_obj365v2_20221223_122105-d9b191f1.pth

- Name: faster-rcnn_r50_fpn_16xb4-1x_objects365v1
  In Collection: Faster R-CNN
  Config: configs/objects365/faster-rcnn_r50_fpn_16xb4-1x_objects365v1.py
  Metadata:
    Training Memory (GB): 11.4
    Epochs: 12
    Training Data: Objects365 v1
    Training Techniques:
      - SGD with Momentum
      - Weight Decay
  Results:
  - Task: Object Detection
    Dataset: Objects365 v1
    Metrics:
      box AP: 19.6
  Weights: https://download.openmmlab.com/mmdetection/v2.0/objects365/faster_rcnn_r50_fpn_16x4_1x_obj365v1/faster_rcnn_r50_fpn_16x4_1x_obj365v1_20221219_181226-9ff10f95.pth

- Name: faster-rcnn_r50-syncbn_fpn_1350k_objects365v1
  In Collection: Faster R-CNN
  Config: configs/objects365/faster-rcnn_r50-syncbn_fpn_1350k_objects365v1.py
  Metadata:
    Training Memory (GB): 8.6
    Iterations: 1350000
    Training Data: Objects365 v1
    Training Techniques:
      - SGD with Momentum
      - Weight Decay
  Results:
  - Task: Object Detection
    Dataset: Objects365 v1
    Metrics:
      box AP: 22.3
  Weights: https://download.openmmlab.com/mmdetection/v2.0/objects365/faster_rcnn_r50_fpn_syncbn_1350k_obj365v1/faster_rcnn_r50_fpn_syncbn_1350k_obj365v1_20220510_142457-337d8965.pth

- Name: faster-rcnn_r50_fpn_16xb4-1x_objects365v2
  In Collection: Faster R-CNN
  Config: configs/objects365/faster-rcnn_r50_fpn_16xb4-1x_objects365v2.py
  Metadata:
    Training Memory (GB): 10.8
    Epochs: 12
    Training Data: Objects365 v1
    Training Techniques:
      - SGD with Momentum
      - Weight Decay
  Results:
  - Task: Object Detection
    Dataset: Objects365 v2
    Metrics:
      box AP: 19.8
  Weights: https://download.openmmlab.com/mmdetection/v2.0/objects365/faster_rcnn_r50_fpn_16x4_1x_obj365v2/faster_rcnn_r50_fpn_16x4_1x_obj365v2_20221220_175040-5910b015.pth
