Collections:
  - Name: MM Grounding DINO
    Metadata:
      Training Data: Objects365, GoldG, GRIT and V3Det
      Training Techniques:
        - AdamW
        - Multi Scale Train
        - Gradient Clip
      Training Resources: 3090 GPUs
      Architecture:
        - Swin Transformer
        - BERT
    README: configs/mm_grounding_dino/README.md
    Code:
      URL:
      Version: v3.0.0

Models:
  - Name: grounding_dino_swin-t_pretrain_obj365_goldg
    In Collection: MM Grounding DINO
    Config: configs/mm_grounding_dino/grounding_dino_swin-t_pretrain_obj365_goldg.py
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 50.4
    Weights: https://download.openmmlab.com/mmdetection/v3.0/mm_grounding_dino/grounding_dino_swin-t_pretrain_obj365_goldg/grounding_dino_swin-t_pretrain_obj365_goldg_20231122_132602-4ea751ce.pth
  - Name: grounding_dino_swin-t_pretrain_obj365_goldg_grit9m
    In Collection: MM Grounding DINO
    Config: configs/mm_grounding_dino/grounding_dino_swin-t_pretrain_obj365_goldg_grit9m.py
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 50.5
    Weights: https://download.openmmlab.com/mmdetection/v3.0/mm_grounding_dino/grounding_dino_swin-t_pretrain_obj365_goldg_grit9m/grounding_dino_swin-t_pretrain_obj365_goldg_grit9m_20231128_200818-169cc352.pth
  - Name: grounding_dino_swin-t_pretrain_obj365_goldg_v3det
    In Collection: MM Grounding DINO
    Config: configs/mm_grounding_dino/grounding_dino_swin-t_pretrain_obj365_goldg_v3det.py
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 50.6
    Weights: https://download.openmmlab.com/mmdetection/v3.0/mm_grounding_dino/grounding_dino_swin-t_pretrain_obj365_goldg_v3det/grounding_dino_swin-t_pretrain_obj365_goldg_v3det_20231218_095741-e316e297.pth
  - Name: grounding_dino_swin-t_pretrain_obj365_goldg_grit9m_v3det
    In Collection: MM Grounding DINO
    Config: configs/mm_grounding_dino/grounding_dino_swin-t_pretrain_obj365_goldg_grit9m_v3det.py
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 50.4
    Weights: https://download.openmmlab.com/mmdetection/v3.0/mm_grounding_dino/grounding_dino_swin-t_pretrain_obj365_goldg_grit9m_v3det/grounding_dino_swin-t_pretrain_obj365_goldg_grit9m_v3det_20231204_095047-b448804b.pth
