Collections:
  - Name: QDTrack
    Metadata:
      Training Data: MOT17, crowdhuman
      Training Techniques:
        - SGD
      Training Resources: 8x V100 GPUs
      Architecture:
        - ResNet
    Paper:
      URL: https://arxiv.org/pdf/2006.06664.pdf
      Title: Quasi-Dense Similarity Learning for Multiple Object Tracking
    README: configs/qdtrack/README.md

Models:
  - Name: qdtrack_faster-rcnn_r50_fpn_8xb2-4e_mot17halftrain_test-mot17halfval
    In Collection: QDTrack
    Config: configs/qdtrack/qdtrack_faster-rcnn_r50_fpn_8xb2-4e_mot17halftrain_test-mot17halfval.py
    Metadata:
      Training Data: MOT17
      Training Memory (GB): 5.83
      Epochs: 4
    Results:
      - Task: Multi-object Tracking
        Dataset: MOT17
        Metrics:
          HOTA: 57.1
          MOTA: 68.1
          IDF1: 68.6
    Weights: https://download.openmmlab.com/mmtracking/mot/qdtrack/mot_dataset/qdtrack_faster-rcnn_r50_fpn_4e_mot17_20220315_145635-76f295ef.pth
