Models:
  - Name: mask-rcnn_r50_fpn_albu-1x_coco
    In Collection: Mask R-CNN
    Config: mask-rcnn_r50_fpn_albu-1x_coco.py
    Metadata:
      Training Memory (GB): 4.4
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 38.0
      - Task: Instance Segmentation
        Dataset: COCO
        Metrics:
          mask AP: 34.5
    Weights: https://download.openmmlab.com/mmdetection/v2.0/albu_example/mask_rcnn_r50_fpn_albu_1x_coco/mask_rcnn_r50_fpn_albu_1x_coco_20200208-ab203bcd.pth
